version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.9.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
      - restore_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix do deps.get, compile --warnings-as-errors
      - save_cache:
          key: dependency-cache-{{ checksum "mix.lock" }}
          paths:
            - deps
      - save_cache:
          key: build-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths:
            - _build
      - run: mix format --check-formatted
      - run: mix dialyzer
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: cover
          destination: coverage_results
