version: 2.1
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/elixir:1.9.2
        environment:
          MIX_ENV: test
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          key: dependency-build-cache-{{ checksum "mix.lock" }}
      - run: mix do deps.get, deps.compile
      - save_cache:
          key: dependency-build-cache-{{ checksum "mix.lock" }}
          paths:
            - ~/.mix
            - _build
            - deps
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
      - restore_cache:
          key: plt-cache-{{ checksum "mix.lock" }}
      - run: mix dialyzer
      - save_cache:
          key: plt-cache-{{ checksum "mix.lock" }}
          paths:
            - ~/.mix
            - _build
            - deps
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: cover
          destination: coverage_results
